// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortfolioBlazor.Data
{
    public partial class History
    {
        public int Id { get; set; }
        public DateTime Timestamp { get; set; }
        public decimal Open { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
        public decimal Close { get; set; }
        public decimal Volume { get; set; }
        public string Symbol { get; set; }

        [NotMapped]
        public decimal Average { get; set; }

        [NotMapped]
        public decimal RecentMax { get; set; }
    }
}