// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PortfolioBlazor.Data
{
    public partial class StockSymbols
    {
        public int Id { get; set; }
        public string StockSymbol { get; set; }
    }
}